### PR TITLE
Issue #85 and easier startup for new contributors

### LINKED ISSUE #85: Make footer stick to bottom
When the page is short, you see below the footer. _weeak_

### PR DESCRIPTION
**Pull request by kyle2829**
Closes #85

### CODE REVIEW

**Comment by mateoclarke** [comment]
Awesome! Thanks for this PR @kyle2829! I see you added a "preinstall" script to help with new contributor setup. Do you think we should add a line in the README about this? Would I be correct to guess it should be around Line 37? https://github.com/cityofaustin/grackl/blob/master/README.md#L37

It looks like this solution to improve footer placement works great for newer versions of Firefox and Chrome! 🎉  But not Safari. Dammit 🍏! I definitely don't see this as a reason not to merge. Just noting that flexbox in Safari has some minor hiccups we should watch out for.

**Comment by kyle2829** [comment]
With regards to the "preinstall," after watching the netlify check spend extra time with the grackle install, I've decided it should be taken out.  I think the better solution is just to add "npm install -g gatsby-cli" as a getting started step in the readme.  

Footer placement works for me on Sierra (Safari 10.1).  Is it broken on High Sierra Safari? (I haven't upgraded yet because everyone I know has had some major time killing issue with it)

**Comment by mateoclarke** [comment]
Cool, that works for me. I appreciate you putting thought into a better onboarding experience! 💯 

Oh yeah, you're right. I'm a sucker and on Safari 11.0.2. Like I said, I wouldn't hesitate to merge regardless.

**Comment by kyle2829** [comment]
I added some flex prefixes which potentially could resolve the safari 11 issue, but I could not test.  It worked on ios safari (for me).  While testing that, I added a meta tag for mobile viewport because clicking the search box would zoom the page awkwardly.

Also, I removed the preinstall and added a step to the readme.

**Pull request merged**
